/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTagIndexRouteImport } from './routes/_authenticated/tag/index'
import { Route as AuthenticatedPostIndexRouteImport } from './routes/_authenticated/post/index'
import { Route as AuthenticatedPostCreatePostRouteImport } from './routes/_authenticated/post/create-post'
import { Route as AuthenticatedPostIdRouteImport } from './routes/_authenticated/post/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTagIndexRoute = AuthenticatedTagIndexRouteImport.update({
  id: '/tag/',
  path: '/tag/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostIndexRoute = AuthenticatedPostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostCreatePostRoute =
  AuthenticatedPostCreatePostRouteImport.update({
    id: '/post/create-post',
    path: '/post/create-post',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPostIdRoute = AuthenticatedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/post/create-post': typeof AuthenticatedPostCreatePostRoute
  '/post': typeof AuthenticatedPostIndexRoute
  '/tag': typeof AuthenticatedTagIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/post/create-post': typeof AuthenticatedPostCreatePostRoute
  '/post': typeof AuthenticatedPostIndexRoute
  '/tag': typeof AuthenticatedTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdRoute
  '/_authenticated/post/create-post': typeof AuthenticatedPostCreatePostRoute
  '/_authenticated/post/': typeof AuthenticatedPostIndexRoute
  '/_authenticated/tag/': typeof AuthenticatedTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/post/$id'
    | '/post/create-post'
    | '/post'
    | '/tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/post/$id' | '/post/create-post' | '/post' | '/tag'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/post/$id'
    | '/_authenticated/post/create-post'
    | '/_authenticated/post/'
    | '/_authenticated/tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tag/': {
      id: '/_authenticated/tag/'
      path: '/tag'
      fullPath: '/tag'
      preLoaderRoute: typeof AuthenticatedTagIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post/': {
      id: '/_authenticated/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post/create-post': {
      id: '/_authenticated/post/create-post'
      path: '/post/create-post'
      fullPath: '/post/create-post'
      preLoaderRoute: typeof AuthenticatedPostCreatePostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPostIdRoute: typeof AuthenticatedPostIdRoute
  AuthenticatedPostCreatePostRoute: typeof AuthenticatedPostCreatePostRoute
  AuthenticatedPostIndexRoute: typeof AuthenticatedPostIndexRoute
  AuthenticatedTagIndexRoute: typeof AuthenticatedTagIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPostIdRoute: AuthenticatedPostIdRoute,
  AuthenticatedPostCreatePostRoute: AuthenticatedPostCreatePostRoute,
  AuthenticatedPostIndexRoute: AuthenticatedPostIndexRoute,
  AuthenticatedTagIndexRoute: AuthenticatedTagIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
